In [1]:
print("Allah is great")

Allah is great

In [2]:
import pandas as pd
import numpy as np
import ast

In [3]:
df = pd.read_csv('RAW_recipes.csv')

In [4]:
df.shape

(231637, 12)

In [5]:
df.columns

Index(['name', 'id', 'minutes', 'contributor_id', 'submitted', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'ingredients',
       'n_ingredients'],
      dtype='object')

In [6]:
df = df[['id', 'name', 'ingredients', 'tags', 'steps', 'minutes' ]]

In [7]:
df.head()

,id,name,ingredients,tags,steps,minutes
0,137739,arriba baked winter squash mexican style,"['winter squash', 'mexican seasoning', 'mixed ...","['60-minutes-or-less', 'time-to-make', 'course...","['make a choice and proceed with recipe', 'dep...",55
1,31490,a bit different breakfast pizza,"['prepared pizza crust', 'sausage patty', 'egg...","['30-minutes-or-less', 'time-to-make', 'course...","['preheat oven to 425 degrees f', 'press dough...",30
2,112140,all in the kitchen chili,"['ground beef', 'yellow onions', 'diced tomato...","['time-to-make', 'course', 'preparation', 'mai...","['brown ground beef in large pot', 'add choppe...",130
3,59389,alouette potatoes,"['spreadable cheese with garlic and herbs', 'n...","['60-minutes-or-less', 'time-to-make', 'course...",['place potatoes in a large pot of lightly sal...,45
4,44061,amish tomato ketchup for canning,"['tomato juice', 'apple cider vinegar', 'sugar...","['weeknight', 'time-to-make', 'course', 'main-...",['mix all ingredients& boil for 2 1 / 2 hours ...,190

In [8]:
df['ingredients'] = df['ingredients'].apply(ast.literal_eval)

In [9]:
df['ingredients'].iloc[0]

['winter squash',
 'mexican seasoning',
 'mixed spice',
 'honey',
 'butter',
 'olive oil',
 'salt']

In [10]:
df['tags'] = df['tags'].apply(ast.literal_eval)

In [11]:
df['tags'].iloc[0]

['60-minutes-or-less',
 'time-to-make',
 'course',
 'main-ingredient',
 'cuisine',
 'preparation',
 'occasion',
 'north-american',
 'side-dishes',
 'vegetables',
 'mexican',
 'easy',
 'fall',
 'holiday-event',
 'vegetarian',
 'winter',
 'dietary',
 'christmas',
 'seasonal',
 'squash']

In [12]:
def clean_tokens(token_list):
    return [i.replace(" ", "").lower() for i in token_list]

In [13]:
df['ingredients_clean'] = df['ingredients'].apply(clean_tokens)

df['tags_clean'] = df['tags'].apply(clean_tokens)

In [14]:
df[['ingredients_clean', 'tags_clean' ]].head()

,ingredients_clean,tags_clean
0,"[wintersquash, mexicanseasoning, mixedspice, h...","[60-minutes-or-less, time-to-make, course, mai..."
1,"[preparedpizzacrust, sausagepatty, eggs, milk,...","[30-minutes-or-less, time-to-make, course, mai..."
2,"[groundbeef, yellowonions, dicedtomatoes, toma...","[time-to-make, course, preparation, main-dish,..."
3,"[spreadablecheesewithgarlicandherbs, newpotato...","[60-minutes-or-less, time-to-make, course, mai..."
4,"[tomatojuice, applecidervinegar, sugar, salt, ...","[weeknight, time-to-make, course, main-ingredi..."

In [15]:
df['features'] = df['ingredients_clean'] + df['tags_clean']

In [16]:
df['features'] = df['features'].apply(lambda x: " ".join(x))

In [17]:
df[['name', 'features']].head()

,name,features
0,arriba baked winter squash mexican style,wintersquash mexicanseasoning mixedspice honey...
1,a bit different breakfast pizza,preparedpizzacrust sausagepatty eggs milk salt...
2,all in the kitchen chili,groundbeef yellowonions dicedtomatoes tomatopa...
3,alouette potatoes,spreadablecheesewithgarlicandherbs newpotatoes...
4,amish tomato ketchup for canning,tomatojuice applecidervinegar sugar salt peppe...

In [35]:
df['name'] = df['name'].fillna('')

In [36]:
df[df['name'].str.contains("pizza", case = False)].head()

,id,name,ingredients,tags,steps,minutes,ingredients_clean,tags_clean,features
1,31490,a bit different breakfast pizza,"[prepared pizza crust, sausage patty, eggs, mi...","[30-minutes-or-less, time-to-make, course, mai...","['preheat oven to 425 degrees f', 'press dough...",30,"[preparedpizzacrust, sausagepatty, eggs, milk,...","[30-minutes-or-less, time-to-make, course, mai...",preparedpizzacrust sausagepatty eggs milk salt...
76,52443,pizza stuffed potato,"[baking potato, mozzarella cheese, tomato sauc...","[30-minutes-or-less, time-to-make, course, mai...","['preheat oven to 450 degrees', 'cut potato in...",25,"[bakingpotato, mozzarellacheese, tomatosauce, ...","[30-minutes-or-less, time-to-make, course, mai...",bakingpotato mozzarellacheese tomatosauce part...
255,60938,pizza pan potato skins,"[potatoes, bacon, cheddar cheese, green onions...","[60-minutes-or-less, time-to-make, course, mai...","['preheat oven to 375f', 'cook the diced bacon...",60,"[potatoes, bacon, cheddarcheese, greenonions, ...","[60-minutes-or-less, time-to-make, course, mai...",potatoes bacon cheddarcheese greenonions oil s...
256,228491,pizza steak,"[plain flour, salt, pepper, boneless eye of ro...","[30-minutes-or-less, time-to-make, course, mai...","['combine flour , salt , & pepper', 'pound int...",30,"[plainflour, salt, pepper, bonelesseyeofroundb...","[30-minutes-or-less, time-to-make, course, mai...",plainflour salt pepper bonelesseyeofroundbeefs...
307,487173,5 minute bread pizza,"[extra virgin olive oil, black olives, white o...","[weeknight, 60-minutes-or-less, time-to-make, ...","['1', 'cover the top of your pizza stone or , ...",45,"[extravirginoliveoil, blackolives, whiteonion,...","[weeknight, 60-minutes-or-less, time-to-make, ...",extravirginoliveoil blackolives whiteonion red...

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
tfidf = TfidfVectorizer(stop_words = 'english')

In [20]:
tfidf_matrix = tfidf.fit_transform(df['features'])

In [21]:
tfidf_matrix.shape

(231637, 15310)

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
indices = pd.Series(df.index, index = df['name']).drop_duplicates()

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
def recommend_recipes(recipe_name, top_n=5):

    recipe_name = recipe_name.lower()

    matches = df[df['name'].str.lower().str.contains(recipe_name, na=False)]

    if matches.empty:
        return "Recipe not found"

    idx = matches.index[0]

    recipe_vector = tfidf_matrix[idx]

    similarity_scores = cosine_similarity(recipe_vector, tfidf_matrix).flatten()

    similar_indices = similarity_scores.argsort()[-top_n-1:-1][::-1]

    return df['name'].iloc[similar_indices].reset_index(drop=True)

In [53]:
def recommend_by_ingredients(ingredients, top_n=5):

    ingredients = ingredients.lower()

    query_vector = tfidf.transform([ingredients])

    similarity_scores = cosine_similarity(query_vector, tfidf_matrix).flatten()

    similar_indices = similarity_scores.argsort()[-top_n:][::-1]

    return df['name'].iloc[similar_indices].reset_index(drop=True)

In [54]:
recommend_recipes("pizza")

0         quick and easy beef pizza
1    eggs with cheese and olive oil
2                 great white pizza
3               pesto chicken pizza
4                     skillet pizza
Name: name, dtype: object

In [55]:
recommend_recipes("chicken")

0                   easy pork chops casserole
1              chicken lickin good pork chops
2                       pork chops  a la vivi
3    crock pot pork chops and cheesy potatoes
4       spiced pork chops  oven and crock pot
Name: name, dtype: object

In [56]:
recommend_recipes("chili")

0                    sandi s auction chili
1    betty crocker s family favorite chili
2               my family s favorite chili
3                     easy chili  crockpot
4                   chunky chili con carne
Name: name, dtype: object

In [57]:
recommend_by_ingredients("chicken tomato garlic")

0            salsa ranch chicken wraps
1            easy slow cooker meatloaf
2                 crabmeat quesadillas
3             rice cooker mexican rice
4    tasty tortilla breakfast sandwich
Name: name, dtype: object

In [58]:
recommend_by_ingredients("egg cheese milk")

0               grilled cheese sandwich pie
1                              fried cheese
2    easy pizza pancakes  thick crepe style
3     microwave macaroni and cheese for one
4                           jiffy chili pie
Name: name, dtype: object